### ISSUE TITLE
Error in Payment

### ISSUE THREAD

**Issue by binarymount** [Makewebbetter/subscriptions-for-woocommerce#149]
Receiving Error log:

2021-10-12T19:01:43+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function Mwb_Subscriptions_Payment_Stripe_Main::mwb_sfw_stripe_force_save_source(), 1 passed in wpsubscription/wp-includes/class-wp-hook.php on line 303 and exactly 2 expected in wpsubscription/wp-content/plugins/subscriptions-for-woocommerce/package/gateways/stripe/class-mwb-subscriptions-payment-stripe-main.php:70
Stack trace:
#0 wpsubscription/wp-includes/class-wp-hook.php(303): Mwb_Subscriptions_Payment_Stripe_Main->mwb_sfw_stripe_force_save_source()
#1 wpsubscription/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 wpsubscription/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php(958): apply_filters()
#3 wpsubscription/wp-content/plugins/subscriptions-for-woocommerce/package/gateways/stripe/class-mwb-subscriptions-payment-stripe-main.php on line 70

**Comment by indresh-cedcoss** [comment]
@binarymount hope your is resolved, so we will closing this isuses
